# Generated by Django 5.2.4 on 2025-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
